### PR TITLE
fixed spacing and resized Technica logo size for 2k+

### PR DESCRIPTION
**Pull request by radhikap0107**
- Resized Technica logo and welcome home logo 
- Fixed spacing between "what you can do" and "hear from our hackers sections"
- Unable to resize the hero-learn text "or learn more below", not sure whats causing the font-size to stay static for all screen sizes

### CODE REVIEW

**Comment by julesparra** [comment]
i'm not able to comment on non-PR code 😢 , but i added this media query to `.hero-learn` in `main.scss` and was able to make "or learn more below!" bigger to match the button on larger screens:
```
@media only screen and (min-width: 2400px) {
      font-size: 200%;
}
```

**Review by julesparra — CHANGES_REQUESTED** [review]
🆑 ose!

**Comment by radhikap0107** [comment]
> i'm not able to comment on non-PR code 😢 , but i added this media query to `.hero-learn` in `main.scss` (starts at line 322) and was able to make "or learn more below!" bigger to match the button on larger screens:
> 
> ```
> @media only screen and (min-width: 2400px) {
>       font-size: 200%;
> }
> ```

Great, that worked! I tried to do the same thing under my media queries for 2k+ screens (starting from line 395 and it didnt work  there, weird)

**Comment by julesparra** [comment]
> > i'm not able to comment on non-PR code 😢 , but i added this media query to `.hero-learn` in `main.scss` (starts at line 322) and was able to make "or learn more below!" bigger to match the button on larger screens:
> > ```
> > @media only screen and (min-width: 2400px) {
> >       font-size: 200%;
> > }
> > ```
> 
> Great, that worked! I tried to do the same thing under my media queries for 2k+ screens (starting from line 395 and it didnt work there, weird)

does adding `!important` to the line work? not ideal but overriding styling might be necessary if u can't identify other styling being applied

**Review by julesparra — APPROVED** [review]
beautiful work 🤍

**Pull request merged**
